name: Stations Human Diff

on:
  schedule:
    # Github limit actually is */10 * * * *
    - cron: '* * * * *'

jobs:
  stations_diff:
    runs-on: ubuntu-latest
    steps:
      - uses: trainline-eu/stations-human-diff@master
        env:
          STATIONS_GITHUB_APP_ID: ${{ secrets.STATIONS_GITHUB_APP_ID }}
          STATIONS_GITHUB_APP_NAME: ${{ secrets.STATIONS_GITHUB_APP_NAME }}
          STATIONS_GITHUB_APP_CLIENT_ID: ${{ secrets.STATIONS_GITHUB_APP_CLIENT_ID }}
          STATIONS_GITHUB_APP_CLIENT_SECRET: ${{ secrets.STATIONS_GITHUB_APP_CLIENT_SECRET }}
          STATIONS_GITHUB_APP_INSTALL_ID: ${{ secrets.STATIONS_GITHUB_APP_INSTALL_ID }}
          STATIONS_GITHUB_APP_PRIVATE_KEY_PEM: ${{ secrets.STATIONS_GITHUB_APP_PRIVATE_KEY_PEM }}
